version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  cooldown:
    default-days: 5
    semver-major-days: 30
    semver-minor-days: 7
    semver-patch-days: 3
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "Technical debt"
    - "python"
