version: 2
updates:
  - package-ecosystem: "all"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "Technical debt"
  - package-ecosystem: "pip" 
    labels:
      - "dependencies"
      - "Technical debt"
      - "python"
