version: "3.3"
services:
  # A Postgresql service as close to production as currently possible
  # To run it as a standalone container:
  #   docker run --name postgres-14.5 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=baracoda_dev -d -p 5432:5432 postgres:14.5
  postgres-14.5:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: baracoda_dev
    volumes:
      - postgres-data:/var/lib/postgresql@14/data

volumes:
  postgres-data:
