# type: ignore

"""create barcodes_groups table

Revision ID: 0898a303eb2a
Revises:
Create Date: 2020-05-12 17:25:45.224290

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0898a303eb2a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barcodes_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("barcodes", sa.Column("barcodes_group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "barcodes", "barcodes_groups", ["barcodes_group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "barcodes", type_="foreignkey")
    op.drop_column("barcodes", "barcodes_group_id")
    op.drop_table("barcodes_groups")
    # ### end Alembic commands ###
